### ISSUE TITLE
ASP000: Calling 'BuildServiceProvider from application code result in additional copy of singletion service being created.

### ISSUE THREAD

**Issue by alitoca** [KevinDockx/DocumentingAspNetCore6API#1]
Hi, 

I am getting this warning any suggestion how to resolve this warning? 

![image](https://user-images.githubusercontent.com/35346639/199034075-f8a77df9-cd07-4c85-9bcd-e5c2b66ccf30.png)

**Comment by KevinDockx** [comment]
As far as I know there's no elegant solution for this until there's a more elegant way to dynamically add swagger docs that depend on version descriptions.  If you're ok with going for a less dynamic approach, you could of course always manually call into setupAction.SwaggerDoc for each version & work with those same static version numbers on the DocInclusionPredicate.

**Comment by alitoca** [comment]
Thanks @KevinDockx, I have suppressed the code analysis warning.
![image](https://user-images.githubusercontent.com/35346639/199777917-6b55f095-50f5-410c-98d4-d51b360ac2e6.png)
